### ISSUE TITLE
Test support with OS X version

### ISSUE THREAD

**Issue by SirYodaJedi** [PollyPlayz/LSWSCU#2]
I suspect that the Mac OS X save files are identical to the Windows save files, as the path reflects that of Windows (according to PCGW):
`~/Library/Application Support/Feral Interactive/LEGO Star Wars Saga/VFS/User/AppData/Roaming/LucasArts/LEGO Star Wars - The Complete Saga/SavedGames/`
I don't have the game, nor a 32-bit Intel Mac to test, but I figured I'd put it out there.

**Comment by PollyPlayz** [comment]
Mac emulation is hard but im looking into it. I think that yes, they will be identical but I wont know till i check

**Comment by PollyPlayz** [comment]
There is no difference between LSW1 PC and LSW1 Mac save files

**Comment by yodadude2003** [comment]
^^^ found this out thanks to me buying a mac mini and a copy of the game on ebay lmao
